version: "3.9"

services:

  s57azj-site:
    image: ghcr.io/aljaz2008/7azj-webpage:latest
    container_name: s57azj-site
    restart: unless-stopped
    networks:
      - npm
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --label-enable
    networks:
      - npm

networks:
  npm:
    external: true