name: Build and Publish Container

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

- name: Build Docker image
  run: docker build -t ghcr.io/aljaz2008/7azj-webpage:latest .

- name: Push Docker image
  run: docker push ghcr.io/aljaz2008/7azj-webpage:latest